export default {
  ADLaMDisplay_400Regular: require('../assets/fonts/ADLaMDisplay_400Regular.ttf'),
  AROneSans_500Medium: require('../assets/fonts/AROneSans_500Medium.ttf'),
  AROneSans_600SemiBold: require('../assets/fonts/AROneSans_600SemiBold.ttf'),
  Inter_400Regular: require('../assets/fonts/Inter_400Regular.ttf'),
  Inter_300Light: require('../assets/fonts/Inter_300Light.ttf'),
  Inter_500Medium: require('../assets/fonts/Inter_500Medium.ttf'),
  Inter_600SemiBold: require('../assets/fonts/Inter_600SemiBold.ttf'),
  Inter_800ExtraBold: require('../assets/fonts/Inter_800ExtraBold.ttf'),
  Inter_700Bold: require('../assets/fonts/Inter_700Bold.ttf'),
  Inter_200ExtraLight: require('../assets/fonts/Inter_200ExtraLight.ttf'),
  NunitoSans_700Bold: require('../assets/fonts/NunitoSans_700Bold.ttf'),
  NunitoSans_500Medium: require('../assets/fonts/NunitoSans_500Medium.ttf'),
  NunitoSans_600SemiBold: require('../assets/fonts/NunitoSans_600SemiBold.ttf'),
  NunitoSans_400Regular: require('../assets/fonts/NunitoSans_400Regular.ttf'),
  Poppins_400Regular: require('../assets/fonts/Poppins_400Regular.ttf'),
  Poppins_500Medium: require('../assets/fonts/Poppins_500Medium.ttf'),
  Poppins_700Bold: require('../assets/fonts/Poppins_700Bold.ttf'),
  Urbanist_400Regular: require('../assets/fonts/Urbanist_400Regular.ttf'),
  Urbanist_600SemiBold: require('../assets/fonts/Urbanist_600SemiBold.ttf'),
  Urbanist_700Bold: require('../assets/fonts/Urbanist_700Bold.ttf'),
};
